Unit Test86;

Interface
Implementation
Uses Crt;
Begin
  IF Test8086<1 Then Begin
    TextColor(15);
    TextBackGround(4);
    Write('                                                                                ');
    Write('    This program uses a 80286 or better                                         ');
    Write('    Please contact us to get a version for a 8086 computer                      ');
    Write('                                                                                ');
    Write('    ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿    ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿                      ');
    Write('    ³ R H Y T H M I C S          ³    ³ or send a Fax to ³                      ');
    Write('    ³ M u e l l e r s t r .  3 4 ³    ³                  ³                      ');
    Write('    ³ C H - 8 0 0 4  Z  r i c h ³    ³ +41 1  730 37 37 ³                      ');
    Write('    ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ    ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ                      ');
    Write('                                                                                ');
    Halt(0);
  End;
  IF Test8086<2 then begin
    Write('                                                                                ');
    Write('    Rhythmics is designed for a 80386 or better.                                ');
    Write('    Please be aware of longer loading and screen building times.                ');
    Write('                                                                                ');
  end;
End.