copy \symbols\CSYM.*
copy \symbols\USERINT.*
copy \symbols\GRINTUNIT.*
copy \symbols\SYMBOLS.*
copy \symbols\PRINTUNIT.*
copy \symbols\HELPUNIT.*
copy \symbols\DMEMUNIT.*
copy \symbols\IMENUUNIT.*
copy \symbols\GRAPHMENU.*
copy \symbols\GRINOUT.*
copy \symbols\DISPMENU.*
copy \symbols\INITSC.*
copy \symbols\GCURUNIT.*
copy \symbols\INOUT.*
copy \symbols\MENUTYP.*
copy \symbols\GRAPH.*
